ptcApp.controller('main-Ctrl', ($scope, config, $firebaseAuth, LxNotificationService) ->
    
    $scope.config = config

    $scope.$on 'alert', ($event, options) ->
        LxNotificationService.success options.text, true

    $firebaseAuth().$onAuthStateChanged(
        (user) ->
            if user
                $scope.$emit 'alert', { type: 'success', text: 'signIn' }
                $scope.user = user
            else
                $scope.user = false
        ,
        (error) -> console.log error
        ,
        (completed) -> console.log completed
    )

)


ptcApp.controller 'auth-Ctrl', [
    '$scope'
    '$firebaseAuth'
    ($scope, $firebaseAuth) ->
        auth = $firebaseAuth()
        auth.$onAuthStateChanged ((user) ->
            console.log user
            if user
                $scope.$emit 'alert',
                    type: 'success'
                    text: 'signIn'
                $scope.user =
                    name: user.displayName
                    email: user.email
                    uid: user.uid
                    photo: user.photoURL
            else
                $scope.user = false
            return
        ), ((error) ->
            console.log error
            return
        ), (completed) ->
            console.log completed
            return
        # login with Facebook

        $scope.signIn = (provider) ->
            auth.$signInWithPopup(provider).then((firebaseUser) ->
                console.log 'Signed in as:', firebaseUser
                return
            ).catch (error) ->
                console.log 'Authentication failed:', error
                return
            return

        $scope.signOut = (provider) ->
            auth.$signOut().then((resp) ->
                console.log 'signOut success:', resp
                $scope.user = false
                return
            ).catch (error) ->
                console.log 'signOut failed:', error
                return
            return

        return
]
ptcApp.controller 'msg-Ctrl', [
    '$scope'
    '$firebaseArray'
    ($scope, $firebaseArray) ->
        ref = firebase.database().ref().child('messages')
        # create a synchronized array
        $scope.messages = $firebaseArray(ref)
        # add new items to the array
        # the message is automatically added to our Firebase database!

        $scope.addMessage = ->
            $scope.messages.$add(text: $scope.newMessageText).then ->
                $scope.newMessageText = null
                return
            return

        # click on `index.html` above to see $remove() and $save() in action
        return
]

# ---
# generated by js2coffee 2.2.0